# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ManoharFrameWork' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ManoharFrameWork

pod 'Alamofire'


  target 'ManoharFrameWorkTests' do
    # Pods for testing
  end
end